[package]
name = "bevy_console"
version = "0.2.5"
edition = "2021"
authors = ["RichoDemus <git@richodemus.com>"]
homepage = "https://github.com/RichoDemus/bevy-console"
repository = "https://github.com/RichoDemus/bevy-console"
description = "dev console for bevy"
license = "MIT"
readme = "README.md"

[dependencies]
bevy = { version = "0.6", default-features = false }
bevy_console_derive = { path = "./bevy_console_derive" }
bevy_console_parser = { path = "./bevy_console_parser" }
bevy_egui = "0.11"

[dev-dependencies]
bevy = "0.6"

[workspace]
members = ["bevy_console_derive", "bevy_console_parser"]
